services:

  postgres:
    image: postgres
    container_name: postgres_container2
    environment:
      POSTGRES_USER: useroot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: controle_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com.br
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5080:80"
    depends_on:
      - postgres

volumes:
  pgdata: